---
title: "Report"
format:
  html:
    code-fold: true
    code-summary: "Show the code"
execute: 
  message: false
  warning: false
---

## Purpose

Display the results of the penguin workflow.

```{r}
library(tidyverse)
library(here)
library(palmerpenguins)
library(gt)

# Load the filtered penguins dataset
penguins_filtered <- read_rds(here("workflow", "data", "processed", "penguins_filtered.rds"))
```

## Summary of Filtered Data

```{r}
penguins_filtered_summary <- penguins_filtered %>%
    group_by(species) %>%
    summarise(
        count = n(),
        mean_body_mass = mean(body_mass_g, na.rm = TRUE),
        mean_flipper_length = mean(flipper_length_mm, na.rm = TRUE),
        mean_bill_length = mean(bill_length_mm, na.rm = TRUE),
        mean_bill_depth = mean(bill_depth_mm, na.rm = TRUE)
    )

penguins_filtered_summary %>%
    gt() %>%
    tab_header(
        title = "Summary of Filtered Penguin Data",
        subtitle = "Excluding Chinstrap Species"
    ) %>%
    cols_label(
        species = "Penguin Species",
        count = "Count",
        mean_body_mass = "Mean Body Mass (g)",
        mean_flipper_length = "Mean Flipper Length (mm)",
        mean_bill_length = "Mean Bill Length (mm)",
        mean_bill_depth = "Mean Bill Depth (mm)"
    ) %>%
    fmt_number(
        columns = vars(mean_body_mass, mean_flipper_length, mean_bill_length, mean_bill_depth),
        decimals = 2
    ) %>%
    tab_spanner(
        label = "Measurements",
        columns = vars(mean_body_mass, mean_flipper_length, mean_bill_length, mean_bill_depth)
    )  %>% 
    tab_source_note(
        source_note = "Data Source: Palmer Penguins Dataset"
    )

```


## Visualizing the Filtered Data

```{r}
# Visualize the distribution of body mass by species
penguins_filtered %>%
    ggplot(aes(x = species, y = body_mass_g, fill = species)) +
    geom_boxplot() +
    labs(
        title = "Body Mass Distribution by Penguin Species",
        x = "Penguin Species",
        y = "Body Mass (g)"
    ) +
    theme_minimal() +
    theme(legend.position = "none")
```